//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "departments")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<Uuid>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::relation_departments_permissions::Entity")]
    RelationDepartmentsPermissions,
    #[sea_orm(has_many = "super::relation_departments_roles::Entity")]
    RelationDepartmentsRoles,
    #[sea_orm(has_many = "super::relation_departments_users::Entity")]
    RelationDepartmentsUsers,
}

impl Related<super::relation_departments_permissions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationDepartmentsPermissions.def()
    }
}

impl Related<super::relation_departments_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationDepartmentsRoles.def()
    }
}

impl Related<super::relation_departments_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationDepartmentsUsers.def()
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_departments_permissions::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_departments_permissions::Relation::Departments
                .def()
                .rev(),
        )
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_departments_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_departments_roles::Relation::Departments
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_departments_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_departments_users::Relation::Departments
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
