//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod departments;
pub mod groups;
pub mod permissions;
pub mod relation_departments_permissions;
pub mod relation_departments_roles;
pub mod relation_departments_users;
pub mod relation_groups_permissions;
pub mod relation_groups_roles;
pub mod relation_groups_users;
pub mod relation_permissions_roles;
pub mod relation_permissions_users;
pub mod relation_roles_users;
pub mod roles;
pub mod settings;
pub mod users;
