//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub mod prelude;

pub mod auth_tokens;
pub mod departments;
pub mod permission_groups;
pub mod permissions;
pub mod relation_permission_groups_departments;
pub mod relation_permission_groups_roles;
pub mod relation_permission_groups_user_groups;
pub mod relation_permission_groups_users;
pub mod relation_permissions_departments;
pub mod relation_permissions_permission_groups;
pub mod relation_permissions_roles;
pub mod relation_permissions_user_groups;
pub mod relation_permissions_users;
pub mod relation_role_groups_departments;
pub mod relation_role_groups_user_groups;
pub mod relation_role_groups_users;
pub mod relation_roles_departments;
pub mod relation_roles_role_groups;
pub mod relation_roles_user_groups;
pub mod relation_roles_users;
pub mod relation_users_departments;
pub mod relation_users_user_groups;
pub mod role_groups;
pub mod roles;
pub mod settings;
pub mod user_groups;
pub mod users;
