//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permission_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub built_in: bool,
    pub parent_id: Option<Uuid>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
    #[sea_orm(has_many = "super::relation_permission_groups_departments::Entity")]
    RelationPermissionGroupsDepartments,
    #[sea_orm(has_many = "super::relation_permission_groups_roles::Entity")]
    RelationPermissionGroupsRoles,
    #[sea_orm(has_many = "super::relation_permission_groups_user_groups::Entity")]
    RelationPermissionGroupsUserGroups,
    #[sea_orm(has_many = "super::relation_permission_groups_users::Entity")]
    RelationPermissionGroupsUsers,
    #[sea_orm(has_many = "super::relation_permissions_permission_groups::Entity")]
    RelationPermissionsPermissionGroups,
}

impl Related<super::relation_permission_groups_departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsDepartments.def()
    }
}

impl Related<super::relation_permission_groups_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsRoles.def()
    }
}

impl Related<super::relation_permission_groups_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsUserGroups.def()
    }
}

impl Related<super::relation_permission_groups_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsUsers.def()
    }
}

impl Related<super::relation_permissions_permission_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsPermissionGroups.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_departments::Relation::Departments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_departments::Relation::PermissionGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_permission_groups::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_permission_groups::Relation::PermissionGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_roles::Relation::PermissionGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_user_groups::Relation::UserGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_user_groups::Relation::PermissionGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_users::Relation::PermissionGroups
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
