//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "permissions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub kind: String,
    pub built_in: bool,
    #[sea_orm(unique)]
    pub code: String,
    pub description: Option<String>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::relation_permissions_departments::Entity")]
    RelationPermissionsDepartments,
    #[sea_orm(has_many = "super::relation_permissions_permission_groups::Entity")]
    RelationPermissionsPermissionGroups,
    #[sea_orm(has_many = "super::relation_permissions_roles::Entity")]
    RelationPermissionsRoles,
    #[sea_orm(has_many = "super::relation_permissions_user_groups::Entity")]
    RelationPermissionsUserGroups,
    #[sea_orm(has_many = "super::relation_permissions_users::Entity")]
    RelationPermissionsUsers,
}

impl Related<super::relation_permissions_departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsDepartments.def()
    }
}

impl Related<super::relation_permissions_permission_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsPermissionGroups.def()
    }
}

impl Related<super::relation_permissions_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsRoles.def()
    }
}

impl Related<super::relation_permissions_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsUserGroups.def()
    }
}

impl Related<super::relation_permissions_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsUsers.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_departments::Relation::Departments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_departments::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl Related<super::permission_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_permission_groups::Relation::PermissionGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_permission_groups::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_roles::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_roles::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_user_groups::Relation::UserGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_user_groups::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_users::Relation::Permissions
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
