//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::permission::Entity as Permission;
pub use super::role::Entity as Role;
pub use super::setting::Entity as Setting;
pub use super::user::Entity as User;
