//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::relation_groups_roles::Entity")]
    RelationGroupsRoles,
    #[sea_orm(has_many = "super::relation_permissions_roles::Entity")]
    RelationPermissionsRoles,
    #[sea_orm(has_many = "super::relation_roles_users::Entity")]
    RelationRolesUsers,
}

impl Related<super::relation_groups_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationGroupsRoles.def()
    }
}

impl Related<super::relation_permissions_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsRoles.def()
    }
}

impl Related<super::relation_roles_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesUsers.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
