//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "role_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub built_in: bool,
    pub parent_id: Option<Uuid>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::relation_role_groups_departments::Entity")]
    RelationRoleGroupsDepartments,
    #[sea_orm(has_many = "super::relation_role_groups_user_groups::Entity")]
    RelationRoleGroupsUserGroups,
    #[sea_orm(has_many = "super::relation_role_groups_users::Entity")]
    RelationRoleGroupsUsers,
    #[sea_orm(has_many = "super::relation_roles_role_groups::Entity")]
    RelationRolesRoleGroups,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::relation_role_groups_departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRoleGroupsDepartments.def()
    }
}

impl Related<super::relation_role_groups_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRoleGroupsUserGroups.def()
    }
}

impl Related<super::relation_role_groups_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRoleGroupsUsers.def()
    }
}

impl Related<super::relation_roles_role_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesRoleGroups.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_role_groups_departments::Relation::Departments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_role_groups_departments::Relation::RoleGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_role_groups::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_roles_role_groups::Relation::RoleGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_role_groups_user_groups::Relation::UserGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_role_groups_user_groups::Relation::RoleGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_role_groups_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_role_groups_users::Relation::RoleGroups
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
