//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "roles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub built_in: bool,
    pub description: Option<String>,
    pub parent_id: Option<Uuid>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::relation_permission_groups_roles::Entity")]
    RelationPermissionGroupsRoles,
    #[sea_orm(has_many = "super::relation_permissions_roles::Entity")]
    RelationPermissionsRoles,
    #[sea_orm(has_many = "super::relation_roles_departments::Entity")]
    RelationRolesDepartments,
    #[sea_orm(has_many = "super::relation_roles_role_groups::Entity")]
    RelationRolesRoleGroups,
    #[sea_orm(has_many = "super::relation_roles_user_groups::Entity")]
    RelationRolesUserGroups,
    #[sea_orm(has_many = "super::relation_roles_users::Entity")]
    RelationRolesUsers,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::relation_permission_groups_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsRoles.def()
    }
}

impl Related<super::relation_permissions_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsRoles.def()
    }
}

impl Related<super::relation_roles_departments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesDepartments.def()
    }
}

impl Related<super::relation_roles_role_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesRoleGroups.def()
    }
}

impl Related<super::relation_roles_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesUserGroups.def()
    }
}

impl Related<super::relation_roles_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesUsers.def()
    }
}

impl Related<super::departments::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_departments::Relation::Departments.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_roles_departments::Relation::Roles
                .def()
                .rev(),
        )
    }
}

impl Related<super::permission_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_roles::Relation::PermissionGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_roles::Relation::Roles
                .def()
                .rev(),
        )
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_roles::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_roles::Relation::Roles
                .def()
                .rev(),
        )
    }
}

impl Related<super::role_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_role_groups::Relation::RoleGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_roles_role_groups::Relation::Roles
                .def()
                .rev(),
        )
    }
}

impl Related<super::user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_user_groups::Relation::UserGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_roles_user_groups::Relation::Roles
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_users::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::relation_roles_users::Relation::Roles.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
