//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tags")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub account_book_id: Uuid,
    pub name: String,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::account_books::Entity",
        from = "Column::AccountBookId",
        to = "super::account_books::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    AccountBooks,
    #[sea_orm(has_many = "super::relation_transactions_tags::Entity")]
    RelationTransactionsTags,
}

impl Related<super::account_books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AccountBooks.def()
    }
}

impl Related<super::relation_transactions_tags::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationTransactionsTags.def()
    }
}

impl Related<super::transactions::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_transactions_tags::Relation::Transactions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_transactions_tags::Relation::Tags
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
