//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "uploads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub hash: String,
    pub name: String,
    pub extension: String,
    pub size: i64,
    pub chunk_size: i32,
    pub status: String,
    pub merged_at: Option<DateTimeWithTimeZone>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::upload_chunks::Entity")]
    UploadChunks,
}

impl Related<super::upload_chunks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UploadChunks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
