//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "upload_chunks")]
pub struct Model {
    pub id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub upload_id: Uuid,
    #[sea_orm(primary_key, auto_increment = false)]
    pub index: i32,
    pub size: i32,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::uploads::Entity",
        from = "Column::UploadId",
        to = "super::uploads::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Uploads,
}

impl Related<super::uploads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Uploads.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
