//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_groups")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    pub description: Option<String>,
    pub parent_id: Option<Uuid>,
    pub is_deleted: bool,
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::relation_permission_groups_user_groups::Entity")]
    RelationPermissionGroupsUserGroups,
    #[sea_orm(has_many = "super::relation_permissions_user_groups::Entity")]
    RelationPermissionsUserGroups,
    #[sea_orm(has_many = "super::relation_role_groups_user_groups::Entity")]
    RelationRoleGroupsUserGroups,
    #[sea_orm(has_many = "super::relation_roles_user_groups::Entity")]
    RelationRolesUserGroups,
    #[sea_orm(has_many = "super::relation_users_user_groups::Entity")]
    RelationUsersUserGroups,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::ParentId",
        to = "Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    SelfRef,
}

impl Related<super::relation_permission_groups_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionGroupsUserGroups.def()
    }
}

impl Related<super::relation_permissions_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationPermissionsUserGroups.def()
    }
}

impl Related<super::relation_role_groups_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRoleGroupsUserGroups.def()
    }
}

impl Related<super::relation_roles_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationRolesUserGroups.def()
    }
}

impl Related<super::relation_users_user_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RelationUsersUserGroups.def()
    }
}

impl Related<super::permission_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permission_groups_user_groups::Relation::PermissionGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permission_groups_user_groups::Relation::UserGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::permissions::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_permissions_user_groups::Relation::Permissions.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_permissions_user_groups::Relation::UserGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::role_groups::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_role_groups_user_groups::Relation::RoleGroups.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_role_groups_user_groups::Relation::UserGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::roles::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_roles_user_groups::Relation::Roles.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_roles_user_groups::Relation::UserGroups
                .def()
                .rev(),
        )
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        super::relation_users_user_groups::Relation::Users.def()
    }
    fn via() -> Option<RelationDef> {
        Some(
            super::relation_users_user_groups::Relation::UserGroups
                .def()
                .rev(),
        )
    }
}

impl ActiveModelBehavior for ActiveModel {}
