[package]
name = "shared"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = { workspace = true }
anyhow = { workspace = true }
base64 = { workspace = true }
blake3 = { workspace = true }
rand = { workspace = true }
rsa = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
utoipa = { workspace = true }
sha2 = { workspace = true }
md5 = { workspace = true }
tokio = { workspace = true }
