[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
argon2 = "0.5.3"
entity = { path = "../entity" }
migration = { path = "../migration" }
sea-orm = "1.1.10"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"
uuid = { version = "1.16.0", features = ["v4"] }
