[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
argon2 = "0.5.3"
chrono = { version = "0.4.41", features = ["serde"] }
entity = { path = "../entity" }
migration = { path = "../migration" }
sea-orm = "1.1.10"
serde = "1.0.219"
serde_json = "1.0.140"
strum = "0.27.1"
strum_macros = "0.27.1"
thiserror = "2.0.12"
utoipa = { version = "5.3.1", features = ["chrono", "uuid", "rc_schema"] }
uuid = { version = "1.16.0", features = ["v4"] }
