[package]
name = "app"
version = "0.1.0"
edition = "2024"

[dependencies]
entity = { path = "../entity" }
migration = { path = "../migration" }
shared = { path = "../shared" }

anyhow = { workspace = true }
argon2 = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
utoipa = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
