[package]
name = "server-template"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[dependencies]
app = { path = "../app" }

anyhow = "1.0.98"
axum = { version = "0.8.3", features = ["ws", "multipart", "macros"] }
axum-extra = "0.10.1"
chrono = "0.4.40"
config = "0.15.11"
dotenvy = "0.15.7"
figlet-rs = "0.1.5"
http = "1.3.1"
reqwest = "0.12.15"
sea-orm = { version = "1.1.10", features = ["sqlx-postgres", "runtime-tokio", "macros", "with-chrono", "with-json", "with-uuid"] }
serde = { version = "1.0.219", features = ["derive", "rc"] }
serde_json = "1.0.140"
sqlx = "0.8.5"
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = ["macros", "rt-multi-thread"] }
tower = "0.5.2"
tower-cookies = "0.11.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
utoipa = { version = "5.3.1", features = ["axum_extras"] }
utoipa-scalar = { version = "0.3.0", features = ["axum"] }
uuid = { version = "1.16.0", features = ["v4"] }

[build-dependencies]
built = { version = "0.7.7", features = ["chrono", "git2", "semver"] }
