[package]
name = "server"
version = "0.1.0"
edition = "2024"
build = "build.rs"
authors = ["Lisiur <lisiurday@gmail.com>"]

[dependencies]
app = { path = "../app" }
shared = { path = "../shared" }

anyhow = { workspace = true }
async-trait = { workspace = true }
axum = { workspace = true }
axum-extra = { workspace = true }
chrono = { workspace = true }
config = { workspace = true }
dotenvy = { workspace = true }
figlet-rs = { workspace = true }
http = { workspace = true }
paste = { workspace = true }
reqwest = { workspace = true }
rsa = { workspace = true }
sea-orm = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sqlx = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
utoipa = { workspace = true }
utoipa-scalar = { workspace = true }
uuid = { workspace = true }
validator = { workspace = true }
strum = { workspace = true }
bytes = { workspace = true }
futures-core = { workspace = true }
tokio-util = { workspace = true }
urlencoding = { workspace = true }

[build-dependencies]
built = { version = "0.7.7", features = ["chrono", "git2", "semver"] }
