//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.10

pub use super::groups::Entity as Groups;
pub use super::permissions::Entity as Permissions;
pub use super::relation_groups_permissions::Entity as RelationGroupsPermissions;
pub use super::relation_groups_roles::Entity as RelationGroupsRoles;
pub use super::relation_groups_users::Entity as RelationGroupsUsers;
pub use super::relation_permissions_roles::Entity as RelationPermissionsRoles;
pub use super::relation_permissions_users::Entity as RelationPermissionsUsers;
pub use super::relation_roles_users::Entity as RelationRolesUsers;
pub use super::roles::Entity as Roles;
pub use super::settings::Entity as Settings;
pub use super::users::Entity as Users;
